# Generated by Django 4.2.13 on 2024-06-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_project_historicaltask_project_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('needs_review', 'Needs Review'), ('completed', 'Completed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('needs_review', 'Needs Review'), ('completed', 'Completed')], max_length=50),
        ),
    ]
