# Generated by Django 4.2.13 on 2024-06-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_historicaltask_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskcomments',
            options={'verbose_name_plural': 'TaskComments'},
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='current_environment',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('dev', 'Dev/Local'), ('uat', 'UAT'), ('staging', 'Staging'), ('preprod', 'Preprod'), ('production', 'Production')], default='not_started', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='current_environment',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('dev', 'Dev/Local'), ('uat', 'UAT'), ('staging', 'Staging'), ('preprod', 'Preprod'), ('production', 'Production')], default='not_started', max_length=50),
        ),
    ]
